% ======================================================
%  2022-1 MIP : Bounding boxes compare
%  05.29 generated by Gyuhyun-Kim
% ======================================================
clear; clc;

labels = {'car','van','truck','bus','motorbike','bicycle','pedestrian','group_of_pedestrians'};
model_name = "X";
% seqs = {'city_3_7','city_7_0','fog_6_0','fog_8_1','junction_1_10','junction_1_11',...
%     'junction_1_12','junction_2_6','junction_3_2','motorway_2_2','night_1_0','night_1_2',...
%     'night_1_4','night_1_5','rain_3_0','rain_4_0','snow_1_0','tiny_foggy'};

% seqs = {'fog_6_0','fog_8_1','junction_1_10','junction_1_11','junction_1_12',...
%     'junction_2_6','junction_3_2','motorway_2_2','night_1_0','night_1_2','night_1_4',...
%     'night_1_5','rain_3_0','rain_4_0','snow_1_0','tiny_foggy','city_3_0','rain_4_1'};

seqs = {'motorway_2_2','night_1_5','snow_1_0','tiny_foggy','city_3_0','rain_4_1'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
seq_name = seqs{1};         % modify here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
format = " [ %f %f %f %f ] %s\t";
pred = fopen(seq_name+"_pred.txt",'r');
true = fopen(seq_name+"_true.txt",'r');

if (exist (model_name+".mat") == 2); load(model_name+".mat");
else; confusion = zeros(8,8); end

while ~feof(pred)
    p_line = fgetl(pred);
    t_line = fgetl(true);
    if length(p_line)*length(t_line) ~= 0
        read = textscan( p_line , format);
        bbox_pred = cell2mat(read(1:4));
        class_pred = read{5};

        read = textscan( t_line , format);
        bbox_true = cell2mat(read(1:4));
        class_true = read{5};

        overlapRatio = bboxOverlapRatio(bbox_true,bbox_pred);
        
        for i = 1:length(class_true)
            [Max,idx] = max(overlapRatio(i,:));
            if Max ~= 0
                [~,idx_true] = find(strcmp(labels,class_true{i}));
                [~,idx_pred] = find(strcmp(labels,class_pred{idx}));
                confusion(idx_true,idx_pred) = confusion(idx_true,idx_pred) + 1;
            end
        end
    end
end

disp(confusion)
save(model_name+'.mat','confusion');

fclose(pred);
fclose(true);

%% Draw confusion matrix
clc;
load(model_name+".mat")

sum_confusion = zeros(4,4);

for i = 1:4
    for j = 1:4
        sum_confusion(i,j) = sum(confusion(2*i-1,2*j-1:2*j)) + sum(confusion(2*i,2*j-1:2*j));
    end
end

sum_confusion(3,:) = [];
sum_confusion(:,3) = [];
disp(sum_confusion)

norm_confusion = zeros(3,3);

for i = 1:3; norm_confusion(i,:) = sum_confusion(i,:)/sum(sum_confusion(i,:)); end
norm_confusion(isnan(norm_confusion)) = 0;
disp(norm_confusion)

n_labels = {'car/van','truck/bus','pedestrian'};
figure("Name",model_name+"_"+seq_name);
heatmap(n_labels,n_labels,norm_confusion*100,"CellLabelFormat","%.2f%%","FontSize",15,"YLabel","True class","XLabel","Predicted class")


%%

norm_confusion = [ 0.635743 0.362457; 0.449134 0.550866 ];
n_labels = {'vehicle','not vehicle'};
heatmap(n_labels,n_labels,norm_confusion*100,"CellLabelFormat","%.2f%%","FontSize",15,"YLabel","True class","XLabel","Predicted class")
