% ======================================================
%  2022-1 MIP : loss figure
%  05.31 generated by Gyuhyun-Kim
% ======================================================
clear; clc;

fotmat = "%q %f ,";

x = 19:20:89999;


f = fopen("metrics_train.json",'r');
train = zeros(1,4500);

i = 1;
while ~feof(f)
    line = fgetl(f);
    read = textscan(line, fotmat);
    read = cell2mat(read(2));
    train(i) = read(9);
    i = i + 1;
end

fclose(f);

f = fopen("metrics_valid.json",'r');
valid = zeros(1,4500);

i = 1;
while ~feof(f)
    line = fgetl(f);
    read = textscan(line, fotmat);
    read = cell2mat(read(2));
    valid(i) = read(9);
    i = i + 1;
end

fclose(f);


figure, clf, hold on, box on, grid on, grid minor
plot(x,train, 'k', x,valid);
legend("train loss","validation loss");
set(gcf, 'position', [0 0 560 300])
xlabel("epoch")
ylabel("loss") ; 
set(gca, 'fontsize', 14)
xlim([0, 90000]) ; 
